project:
  name: marshfield
  place_name: Marshfield, MA, USA
  country: US
  model_crs: EPSG:26919
  reference_crs: EPSG:4326

# Location type
flood_setting: coastal

# Flood drivers
event_drivers:
- coastal_water_level
- rainfall
- soil_moisture

coastal_waves: true

# Sea-level-rise offsets for years 2050 and 2100
scenarios:
  base:
    slr_offset_m: 0.0
  noaa_int_2050:
    slr_offset_m: 0.3
  noaa_int_2100:
    slr_offset_m: 1.1

includes:
  grid: grid.yaml
  sfincs: sfincs.yaml
  snapwave: snapwave.yaml
