# OpenDSS and PowerModelsONM switch rendering
"""OpenDSS and PowerModelsONM export helpers for synthesized switches."""

from __future__ import annotations
import pandas as pd

onm_settings_schema_version = "stage_b_onm_settings.v0.1"

def render_switches_dss(controllable_switches: pd.DataFrame) -> str:
    """Render synthesized Controllable Switches as OpenDSS switch lines."""

    lines_out = [
        "! Marshfield Stage B synthesized Controllable Switches",
        "! Generated by add_infra.ipynb Infrastructure Step: controllable_switch_synthesis",
        "! Critical-load-boundary switches are deferred until critical-facility artifacts validate.",
    ]
    for row in controllable_switches.itertuples(index=False):
        element_name = row.opendss_element.split(".", 1)[1]
        action = "Open" if row.initial_state == "open" else "Close"
        normal = "Open" if row.normal_state == "open" else "Close"
        if row.switch_role == "sectionalizing" and bool(row.opens_existing_line):
            original_line = str(row.associated_line_name)
            linecode = str(row.associated_linecode) if pd.notna(row.associated_linecode) else ""
            units = str(row.associated_units) if pd.notna(row.associated_units) else "m"
            length_m = float(row.associated_length_m) if pd.notna(row.associated_length_m) else 2.0
            segment_length = max(length_m / 2.0, 0.001)
            linecode_clause = f" Linecode={linecode}" if linecode else ""
            switch_bus_a = f"{element_name}_a"
            switch_bus_b = f"{element_name}_b"
            lines_out.extend(
                [
                    f"Disable Line.{original_line}",
                    f"New Line.{element_name}_seg_a Bus1={row.from_bus} Bus2={switch_bus_a} Phases={row.phases}{linecode_clause} Length={segment_length:.6g} units={units}",
                    f"New Line.{element_name} Bus1={switch_bus_a} Bus2={switch_bus_b} Phases={row.phases} Switch=Yes",
                    "~ R1=0.001 X1=0 R0=0.001 X0=0 C1=0 C0=0 Length=0.001 units=km",
                    f"New SwtControl.{element_name} SwitchedObj=Line.{element_name} SwitchedTerm=1",
                    f"~ Action={action} Normal={normal} Lock=No",
                    f"New Line.{element_name}_seg_b Bus1={switch_bus_b} Bus2={row.to_bus} Phases={row.phases}{linecode_clause} Length={segment_length:.6g} units={units}",
                ]
            )
            continue
        lines_out.extend(
            [
                f"New Line.{element_name} Bus1={row.from_bus} Bus2={row.to_bus} Phases={row.phases} Switch=Yes",
                "~ R1=0.001 X1=0 R0=0.001 X0=0 C1=0 C0=0 Length=0.001 units=km",
                f"New SwtControl.{element_name} SwitchedObj=Line.{element_name} SwitchedTerm=1",
                f"~ Action={action} Normal={normal} Lock=No",
            ]
        )
    return "\n".join(lines_out) + "\n"


def render_onm_settings(controllable_switches: pd.DataFrame) -> dict:
    """Emit PowerModelsONM switch settings sidecar fields not expressible in DSS."""

    switch_section: dict[str, dict] = {}
    for row in controllable_switches.itertuples(index=False):
        switch_key = row.opendss_element.split(".", 1)[1]
        switch_section[switch_key] = {
            "dispatchable": "YES" if bool(row.dispatchable) else "NO",
            "status": "ENABLED" if str(row.status) == "enabled" else "DISABLED",
            "state": "OPEN" if str(row.normal_state) == "open" else "CLOSED",
            "switch_role": str(row.switch_role),
            "switch_id": str(row.switch_id),
        }
    return {
        "schema_version": onm_settings_schema_version,
        "infrastructure_step": "controllable_switch_synthesis",
        "settings": {
            "switch": switch_section,
        },
    }


def connected_component_count(
    edge_frame: pd.DataFrame,
    buses: pd.DataFrame,
    transformers: pd.DataFrame | None = None,
) -> tuple[int, pd.Series]:
    """Count connected bus components in an edge table."""

    parent = {bus: bus for bus in buses["bus"].dropna().unique()}

    def find(item):
        parent.setdefault(item, item)
        while parent[item] != item:
            parent[item] = parent[parent[item]]
            item = parent[item]
        return item

    def union(left, right):
        left_root = find(left)
        right_root = find(right)
        if left_root != right_root:
            parent[right_root] = left_root

    for edge in edge_frame.itertuples(index=False):
        union(edge.from_bus, edge.to_bus)

    if (
        transformers is not None
        and not transformers.empty
        and "winding_buses" in transformers.columns
    ):
        for row in transformers.itertuples(index=False):
            windings = [
                bus.strip()
                for bus in str(row.winding_buses).split(",")
                if bus.strip()
            ]
            unique: list[str] = []
            seen: set[str] = set()
            for bus in windings:
                if bus in seen:
                    continue
                seen.add(bus)
                unique.append(bus)
            if len(unique) < 2:
                continue
            hub = unique[0]
            for other in unique[1:]:
                union(hub, other)

    roots = pd.Series([find(bus) for bus in buses["bus"].dropna().unique()])
    sizes = roots.value_counts()
    return int(len(sizes)), sizes


def derive_switch_bounded_load_block_summary(
    lines: pd.DataFrame,
    buses: pd.DataFrame,
    controllable_switches: pd.DataFrame,
    transformers: pd.DataFrame | None = None,
) -> pd.Series:
    """Summarize static blocks after opening all synthesized sectionalizers.

    Transformer winding buses are non-switchable topology bridges, so they must
    connect components for this summary.
    """

    line_edges = lines[lines["line_class"].fillna("line").eq("line")].copy()
    baseline_components, _baseline_sizes = connected_component_count(
        line_edges, buses, transformers
    )
    opened_existing_lines = set(
        controllable_switches.loc[
            controllable_switches["opens_existing_line"].fillna(False),
            "associated_line_name",
        ].dropna()
    )
    block_edges = line_edges[~line_edges["line_name"].isin(opened_existing_lines)]
    block_count, block_sizes = connected_component_count(
        block_edges, buses, transformers
    )
    return pd.Series(
        {
            "baseline_components": baseline_components,
            "switch_bounded_blocks": block_count,
            "switch_bounded_nontrivial_blocks": int((block_sizes > 1).sum()),
            "switch_bounded_single_bus_blocks": int((block_sizes == 1).sum()),
            "median_block_bus_count": float(block_sizes.median()) if not block_sizes.empty else 0.0,
            "max_block_bus_count": int(block_sizes.max()) if not block_sizes.empty else 0,
            "opened_existing_lines_for_blocks": len(opened_existing_lines),
        }
    )




# Load uncertainty bounds

"""Per-load uncertainty bounds for robust restoration optimization.

Implements the per-(load, timestep) uncertainty set consumed by the two-stage
Robust Partitioning and Operation Problem (RPOP). The uncertainty model defines

    s_d^{phi} = s_d^{0,phi} + u_d^{phi},     underline{s_d^{phi}} <= s_d^{phi} <= overline{s_d^{phi}}

i.e. each load's realized demand lies in a per-load band around a nominal
demand. The implementation supports spatially clustered load uncertainty:
loads in the same cluster respond simultaneously to the worst-case realization.
This reduces the cardinality of the inner max problem from one realization per
load/phase to one realization per cluster.

This module assembles the bound table the master/subproblem consumes:

* ``nominal_kw`` comes from the event-windowed load profile produced by
  ``power.exports.slice_annual_profile_to_event_window`` after
  diversity-preserving nodal assignment in
  ``power.resilience.assign_nodal_load_profiles``.
* The default symmetric band is ±20%, matching the current stress-test policy.
* The cluster id defaults to the Switch-Bounded Load Block id
  (``simulated_data_protocol.md`` §"switch_bounded_load_blocks"), so loads
  inside the same block share a cluster and avoid inventing a new spatial
  grouping.
"""


from collections.abc import Mapping, Sequence
from typing import Any


load_uncertainty_schema_version = "marshfield_load_uncertainty.v0.1"
default_load_uncertainty_band_fraction = 0.20


def build_load_uncertainty_bounds(
    nominal_windows: Sequence[Mapping[str, Any]],
    *,
    event_id: str,
    mc_draw: int,
    band_fraction: float = default_load_uncertainty_band_fraction,
) -> list[dict[str, Any]]:
    """Build per-(load, timestep) uncertainty bounds for the RPOP solver.

    Each ``nominal_windows`` entry must carry ``load_asset_id``, ``block_id``,
    ``feeder_id``, and ``values`` (a sequence of nominal kW values, one per
    optimization timestep). Output rows expand to one record per
    (load_asset_id, timestep).
    """

    if band_fraction < 0.0:
        raise ValueError("band_fraction must be non-negative")

    rows: list[dict[str, Any]] = []
    for window in nominal_windows:
        load_asset_id = str(window["load_asset_id"])
        cluster_id = str(window["block_id"])
        feeder_id = str(window.get("feeder_id", ""))
        for timestep, nominal_kw in enumerate(window["values"]):
            nominal = float(nominal_kw)
            rows.append(
                {
                    "event_id": event_id,
                    "mc_draw": mc_draw,
                    "timestep": timestep,
                    "load_asset_id": load_asset_id,
                    "cluster_id": cluster_id,
                    "feeder_id": feeder_id,
                    "nominal_kw": nominal,
                    "lower_kw": nominal * (1.0 - band_fraction),
                    "upper_kw": nominal * (1.0 + band_fraction),
                    "band_fraction": band_fraction,
                    "schema_version": load_uncertainty_schema_version,
                }
            )
    return rows

# Event-window bundle

"""Slice a full annual profile down to the PowerModelsONM event window.

PowerModelsONM operates over a finite restoration horizon. EULP /
ResStock / ComStock source profiles are 8760-hour annual series. This module
maps a FLOOD-RM/SFINCS event start timestamp to the corresponding hour-of-year
in the annual profile and returns a contiguous slice of length
``horizon_hours``.

The default horizon is 72 hours, matching the FEMA Community Lifelines
Stabilization horizon used by the DER inventory and REopt resilience sizing.
"""


import json
import re
from dataclasses import dataclass
from datetime import datetime, timedelta, timezone
from typing import Any, Sequence

import pandas as pd

from power.resilience import build_archetype_load_profile


default_fema_lifelines_horizon_hours = 72
hours_per_year = 8760


def _slug(value: str) -> str:
    normalized = re.sub(r"[^a-z0-9]+", "_", value.lower()).strip("_")
    return normalized or "unknown"


@dataclass(frozen=True)
class EventWindow:
    """A contiguous slice of an annual profile aligned to an event start.

    ``values`` has length ``horizon_hours`` and is wrapped across the year
    boundary if the event extends past December 31 23:00 UTC.
    """

    values: list[float]
    start_hour_of_year: int
    end_hour_of_year: int
    horizon_hours: int
    weather_year: int
    event_start_utc: datetime
    wrapped_across_year_boundary: bool


def hour_of_year(timestamp: datetime) -> int:
    """Return the zero-indexed hour-of-year for a UTC timestamp.

    January 1 00:00 UTC maps to 0; January 1 14:00 UTC maps to 14; for
    non-leap years December 31 23:00 UTC maps to 8759.
    """

    if timestamp.tzinfo is None:
        raise ValueError("hour_of_year requires a timezone-aware (UTC) timestamp")
    utc_timestamp = timestamp.astimezone(timezone.utc)
    year_start = datetime(utc_timestamp.year, 1, 1, tzinfo=timezone.utc)
    delta = utc_timestamp - year_start
    return int(delta.total_seconds() // 3600)


def slice_annual_profile_to_event_window(
    annual_profile: Sequence[float],
    *,
    event_start_utc: datetime,
    weather_year: int,
    horizon_hours: int = default_fema_lifelines_horizon_hours,
) -> EventWindow:
    """Slice an 8760-hour profile to ``horizon_hours`` starting at the event.

    The slice wraps across the year boundary when needed so the returned
    window always has length ``horizon_hours``.
    """

    if event_start_utc.tzinfo is None:
        raise ValueError("event_start_utc must be timezone-aware (UTC)")
    if len(annual_profile) != hours_per_year:
        raise ValueError(
            f"annual_profile must have length {hours_per_year}; "
            f"got {len(annual_profile)}"
        )
    if horizon_hours <= 0:
        raise ValueError("horizon_hours must be positive")

    start_hour = hour_of_year(event_start_utc)
    raw_end_hour = start_hour + horizon_hours
    wrapped = raw_end_hour > hours_per_year

    if not wrapped:
        values = list(annual_profile[start_hour:raw_end_hour])
    else:
        tail = list(annual_profile[start_hour:hours_per_year])
        head = list(annual_profile[0 : raw_end_hour - hours_per_year])
        values = tail + head

    return EventWindow(
        values=values,
        start_hour_of_year=start_hour,
        end_hour_of_year=raw_end_hour,
        horizon_hours=horizon_hours,
        weather_year=weather_year,
        event_start_utc=event_start_utc.astimezone(timezone.utc),
        wrapped_across_year_boundary=wrapped,
    )


def build_event_window_bundle(
    *,
    event_start: datetime,
    horizon_hours: int,
    load_profiles: pd.DataFrame,
    blocks: pd.DataFrame,
    sandbox_id: str,
    uncertainty_band: float = 0.20,
    event_id: str = "preview_event",
    mc_draw: int = 0,
) -> dict[str, Any]:
    """Build a notebook-preview ONM event-window demand bundle.

    ``load_profile_assignments.parquet`` records the profile assignment and
    provenance, while the current Stage B preview regenerates synthetic 8760
    archetype profiles from that provenance. This wrapper keeps the notebook
    readable and returns the four event-window slices needed for inspection:
    nodal demand windows, per-load uncertainty bands, block demand summaries,
    and scalar bundle metadata.
    """

    event_start_utc = _coerce_utc(event_start)
    load_to_block = _load_asset_to_block_id(blocks, sandbox_id=sandbox_id)
    nodal_demand: list[dict[str, Any]] = []
    nominal_windows: list[dict[str, Any]] = []
    weather_years: set[int] = set()

    for row in load_profiles.itertuples(index=False):
        record = row._asdict()
        provenance = _profile_provenance(record)
        archetype = {
            "schedule_overlay": provenance.get("schedule_overlay", "business_hours"),
            "profile_source": record.get("profile_source"),
            "source_building_type": record.get("source_building_type"),
            "source_geography": record.get("source_geography"),
        }
        weather_year = int(record.get("weather_year") or event_start_utc.year)
        weather_years.add(weather_year)
        annual_profile = build_archetype_load_profile(
            archetype,
            peak_kw=float(record["peak_kw"]),
        )
        window = slice_annual_profile_to_event_window(
            annual_profile,
            event_start_utc=event_start_utc,
            weather_year=weather_year,
            horizon_hours=horizon_hours,
        )
        load_asset_id = str(record["load_asset_id"])
        block_id = load_to_block.get(load_asset_id, "unassigned_block")
        demand_row = {
            "load_asset_id": load_asset_id,
            "loadshape_id": str(record["loadshape_id"]),
            "block_id": block_id,
            "feeder_id": "" if pd.isna(record.get("feeder_id")) else str(record.get("feeder_id")),
            "customer_class": str(record.get("customer_class", "")),
            "peak_kw": float(record["peak_kw"]),
            "values": window.values,
            "start_hour_of_year": window.start_hour_of_year,
            "wrapped_across_year_boundary": window.wrapped_across_year_boundary,
        }
        nodal_demand.append(demand_row)
        nominal_windows.append(
            {
                "load_asset_id": load_asset_id,
                "block_id": block_id,
                "feeder_id": demand_row["feeder_id"],
                "values": window.values,
            }
        )

    uncertainty_bands = build_load_uncertainty_bounds(
        nominal_windows,
        event_id=event_id,
        mc_draw=mc_draw,
        band_fraction=uncertainty_band,
    )
    block_summary = _block_demand_summary(nodal_demand)
    event_end = event_start_utc + timedelta(hours=horizon_hours)

    return {
        "event_start": event_start_utc.isoformat(),
        "event_end": event_end.isoformat(),
        "horizon_hours": horizon_hours,
        "timestep_count": horizon_hours,
        "load_profile_count": int(len(load_profiles)),
        "block_count": len(block_summary),
        "uncertainty_band": uncertainty_band,
        "uncertainty_row_count": len(uncertainty_bands),
        "weather_years": sorted(weather_years),
        "nodal_demand": nodal_demand,
        "uncertainty_bands": uncertainty_bands,
        "block_demand_summary": block_summary,
    }


def _coerce_utc(timestamp: datetime) -> datetime:
    if timestamp.tzinfo is None:
        return timestamp.replace(tzinfo=timezone.utc)
    return timestamp.astimezone(timezone.utc)


def _profile_provenance(record: dict[str, Any]) -> dict[str, Any]:
    raw = record.get("source_provenance")
    if raw is None or pd.isna(raw):
        return {}
    try:
        return json.loads(str(raw))
    except json.JSONDecodeError:
        return {}


def _load_asset_to_block_id(blocks: pd.DataFrame, *, sandbox_id: str) -> dict[str, str]:
    out: dict[str, str] = {}
    if blocks.empty or "buses_json" not in blocks.columns:
        return out
    for row in blocks.itertuples(index=False):
        block_id = str(row.block_id)
        for bus in json.loads(row.buses_json):
            bus_asset_token = _slug(str(bus))
            out[f"{sandbox_id}:asset:load_buses:{bus}"] = block_id
            out[f"{sandbox_id}:asset:loads:{bus}"] = block_id
            out[f"{sandbox_id}:asset:load_buses:{bus_asset_token}"] = block_id
            out[f"{sandbox_id}:asset:loads:{bus_asset_token}"] = block_id
    return out


def _block_demand_summary(nodal_demand: Sequence[dict[str, Any]]) -> list[dict[str, Any]]:
    by_block: dict[str, dict[str, Any]] = {}
    for row in nodal_demand:
        block_id = str(row["block_id"])
        entry = by_block.setdefault(
            block_id,
            {
                "block_id": block_id,
                "load_count": 0,
                "peak_window_kw": 0.0,
                "energy_window_kwh": 0.0,
            },
        )
        values = [float(value) for value in row["values"]]
        entry["load_count"] += 1
        entry["peak_window_kw"] += max(values) if values else 0.0
        entry["energy_window_kwh"] += sum(values)
    return sorted(by_block.values(), key=lambda item: item["block_id"])


# Artifact-first PowerModelsONM export

"""Artifact-first PowerModelsONM export adapter for Marshfield."""


import json
import re
import shutil
from dataclasses import dataclass
from pathlib import Path

import pandas as pd

from power.resilience import build_archetype_load_profile


@dataclass(frozen=True)
class PowerModelsOnmExport:
    """Paths emitted by the PowerModelsONM export adapter."""

    output_dir: Path
    network_dss_path: Path
    settings_path: Path
    linecodes_path: Path
    transformers_path: Path
    lines_path: Path
    loads_path: Path
    loadshapes_path: Path
    ders_path: Path
    switches_path: Path
    buscoords_path: Path
    stage_b_metadata_path: Path
    manifest_path: Path


@dataclass(frozen=True)
class OnmRunBundle:
    """Paths emitted for one event-conditioned ONM run window."""

    bundle_dir: Path
    events_path: Path
    runtime_args_path: Path
    nominal_load_window_path: Path
    load_uncertainty_path: Path
    block_demand_summary_path: Path
    run_manifest_path: Path


_bus_fields = ("Bus1", "Bus2", "Bus")
_fault_study_source_impedance = "Z1=[0.25, 0.25] Z0=[0.25, 0.25]"


def _prefix_bus_token(token: str, feeder_id: str) -> str:
    stripped = token.strip()
    if not stripped or stripped.startswith(f"{feeder_id}__"):
        return stripped
    if stripped[0] in "([{" or stripped[0] in "\"'":
        return stripped
    return f"{feeder_id}__{stripped}"


def _prefix_bus_value(value: str, feeder_id: str) -> str:
    if value.startswith("(") and value.endswith(")"):
        inner = value[1:-1]
        return "(" + ", ".join(_prefix_bus_token(part.strip(), feeder_id) for part in inner.split(",")) + ")"
    return _prefix_bus_token(value, feeder_id)


def _prefix_bus_references(line: str, feeder_id: str) -> str:
    for field in _bus_fields:
        line = re.sub(
            rf"\b{field}=([^\s]+)",
            lambda match: f"{field}={_prefix_bus_value(match.group(1), feeder_id)}",
            line,
            flags=re.IGNORECASE,
        )
    line = re.sub(
        r"\bBuses=\(([^)]*)\)",
        lambda match: "Buses=("
        + ", ".join(_prefix_bus_token(part.strip(), feeder_id) for part in match.group(1).split(","))
        + ")",
        line,
        flags=re.IGNORECASE,
    )
    return line


def _remove_default_enabled_token(line: str) -> str:
    """Drop OpenDSS default enabled tokens that PowerModelsDistribution rejects."""

    return re.sub(r"\s+Enabled=True\b", "", line, flags=re.IGNORECASE)


def _prefixed_component_text(feeder_dir: Path, filename: str, feeder_id: str) -> str:
    path = feeder_dir / filename
    if not path.exists():
        return ""
    rows = []
    for raw in path.read_text(encoding="utf-8").splitlines():
        text = raw.strip()
        if not text:
            continue
        rows.append(_remove_default_enabled_token(_prefix_bus_references(text, feeder_id)))
    return "\n".join(rows)


def _format_dss_float(value: float) -> str:
    return f"{value:.10g}"


def _normalize_placeholder_impedance_matrix(match: re.Match[str]) -> str:
    def scale_token(token: re.Match[str]) -> str:
        value = float(token.group(0))
        if abs(value) >= 100.0:
            value /= 1_000_000.0
        return _format_dss_float(value)

    return re.sub(r"(?<![A-Za-z])[-+]?\d+(?:\.\d+)?(?:[eE][-+]?\d+)?", scale_token, match.group(0))


def _normalize_linecode_impedance_text(dss_text: str) -> str:
    rows = []
    for line in dss_text.splitlines():
        if re.match(r"\s*new\s+LineCode\.", line, flags=re.IGNORECASE):
            for field in ("RMatrix", "XMatrix"):
                line = re.sub(
                    rf"{field}=\([^)]*\)",
                    _normalize_placeholder_impedance_matrix,
                    line,
                    flags=re.IGNORECASE,
                )
        rows.append(line)
    return "\n".join(rows)


def _drop_named_lines(dss_text: str, line_names: set[str]) -> str:
    rows = []
    for line in dss_text.splitlines():
        match = re.match(r"new\s+Line\.([^\s]+)\s+", line, flags=re.IGNORECASE)
        if match is not None and match.group(1) in line_names:
            continue
        rows.append(line)
    return "\n".join(rows)


def _switches_text_without_disable_commands_from_text(switches_text: str) -> str:
    rows = []
    skip_continuation = False
    for line in switches_text.splitlines():
        stripped = line.strip()
        lowered = stripped.lower()
        if lowered.startswith("disable "):
            skip_continuation = False
            continue
        if lowered.startswith("new swtcontrol."):
            skip_continuation = True
            continue
        if skip_continuation and lowered.startswith("~"):
            continue
        skip_continuation = False
        rows.append(line)
    return "\n".join(rows) + "\n"


def _safe_dss_name(value: str) -> str:
    return re.sub(r"[^A-Za-z0-9_]+", "_", value).strip("_").lower()


def _loadshape_assignments(
    *,
    smart_ds_compat_dir: Path,
    asset_registry_dir: Path,
    profiles_dir: Path,
) -> tuple[dict[str, str], str]:
    profile_assignments_path = smart_ds_compat_dir / "load_profile_assignments.parquet"
    if not profile_assignments_path.exists():
        return {}, "! No load_profile_assignments.parquet artifact found.\n"

    assignments = pd.read_parquet(profile_assignments_path)
    assets = pd.read_parquet(smart_ds_compat_dir / "assets.parquet")
    loads = pd.read_csv(asset_registry_dir / "loads.csv")
    asset_bus_by_id = dict(zip(assets["asset_id"].astype(str), assets["bus"].astype(str), strict=False))

    shape_by_load_name: dict[str, str] = {}
    loadshape_lines: list[str] = []
    profiles_dir.mkdir(parents=True, exist_ok=True)
    for row in assignments.itertuples(index=False):
        bus = asset_bus_by_id.get(str(row.load_asset_id))
        if bus is None:
            continue
        shape_name = _safe_dss_name(str(row.loadshape_id))
        archetype = {
            "profile_source": row.profile_source,
            "source_building_type": row.source_building_type,
            "source_geography": row.source_geography,
            "schedule_overlay": json.loads(row.source_provenance).get("schedule_overlay", "business_hours"),
        }
        profile = build_archetype_load_profile(archetype, peak_kw=float(row.peak_kw))
        profile_path = profiles_dir / f"{shape_name}.csv"
        profile_path.write_text("\n".join(f"{value:.6f}" for value in profile) + "\n", encoding="utf-8")
        loadshape_lines.append(
            f"New LoadShape.{shape_name} npts=8760 interval=1 mult=(file=profiles/{shape_name}.csv) UseActual=Yes"
        )
        for load in loads.loc[loads["bus"].astype(str).eq(bus), "load_name"].astype(str):
            shape_by_load_name[load] = shape_name

    return shape_by_load_name, "\n".join(loadshape_lines) + ("\n" if loadshape_lines else "")


def _append_yearly_loadshape(line: str, loadshape_by_load_name: dict[str, str]) -> str:
    match = re.match(r"new\s+Load\.([^\s]+)\s+", line, flags=re.IGNORECASE)
    if match is None:
        return line
    loadshape = loadshape_by_load_name.get(match.group(1))
    if loadshape is None or " yearly=" in line.lower():
        return line
    return f"{line} Yearly={loadshape}"


def _der_generators_text(
    *,
    smart_ds_compat_dir: Path,
    feeder_ids: set[str] | None = None,
) -> tuple[str, dict[str, int], dict[str, dict]]:
    der_path = smart_ds_compat_dir / "der_inventory.parquet"
    profile_path = smart_ds_compat_dir / "load_profile_assignments.parquet"
    if not der_path.exists() or not profile_path.exists():
        return (
            "! DER inventory or load-profile assignment artifact missing.\n",
            {"provisional": 0, "reopt_sized": 0},
            {},
        )

    ders = pd.read_parquet(der_path)
    if feeder_ids:
        if "feeder_id" in ders.columns:
            ders = ders[ders["feeder_id"].astype(str).isin(feeder_ids)].copy()
        elif "bus" in ders.columns:
            ders = ders[
                ders["bus"].astype(str).map(lambda bus: bus.split("__", 1)[0]).isin(feeder_ids)
            ].copy()
    profiles = pd.read_parquet(profile_path)
    _peak_by_load_asset_id = dict(
        zip(profiles["load_asset_id"].astype(str), profiles["peak_kw"].astype(float), strict=False)
    )

    rows: list[str] = []
    dss_settings: dict[str, dict] = {}
    provisional = 0
    reopt_sized = 0
    for der in ders.itertuples(index=False):
        if str(der.assignment_status) != "assigned" or not bool(der.gfm_capable):
            continue
        name = _safe_dss_name(str(der.der_id))
        phases = int(float(der.phases)) if pd.notna(der.phases) else 3
        kv = float(der.nominal_voltage_kv) if pd.notna(der.nominal_voltage_kv) else 0.208
        genset_kw = float(der.genset_kw) if pd.notna(der.genset_kw) else None
        is_reopt_sized = str(getattr(der, "placement_rule", "")) == "reopt_resilience_sizing"
        if not is_reopt_sized:
            provisional += 1
            rows.append(f"! held_out_until_reopt_sized; source der_id={der.der_id}")
            continue
        reopt_sized += 1
        if genset_kw is None or genset_kw <= 0.0:
            rows.append(f"! reopt_sized_no_positive_genset; source der_id={der.der_id}")
            continue
        rows.append(f"! reopt_sized; source der_id={der.der_id}")
        rows.append(
            f"New Generator.{name} Bus1={der.bus} Phases={phases} kV={kv:.6g} "
            f"kW={genset_kw:.6g} pf=1 Model=1"
        )
        dss_settings[f"Generator.{name}"] = {
            "inverter": "GRID_FORMING",
        }
    if provisional and not reopt_sized:
        rows.insert(0, "! No REopt-sized DER rows available; evidence rows held out of live OpenDSS generators.")
    return "\n".join(rows) + ("\n" if rows else ""), {
        "provisional": provisional,
        "reopt_sized": reopt_sized,
    }, dss_settings


def _prefixed_buscoords_text(feeder_dir: Path, feeder_id: str) -> str:
    path = feeder_dir / "BusCoords.dss"
    if not path.exists():
        return ""
    rows = []
    for raw in path.read_text(encoding="utf-8").splitlines():
        text = raw.strip()
        if text.lower().startswith("setbusxy "):
            parts = text.split(maxsplit=2)
            if len(parts) == 3:
                coordinates = parts[2].split()
                if len(coordinates) >= 2:
                    rows.append(f"{parts[0]} Bus={feeder_id}__{parts[1]} X={coordinates[0]} Y={coordinates[1]}")
                continue
        if text.lower().startswith("setkvbase "):
            continue
        rows.append(text)
    return "\n".join(rows)


def _split_pmonm_settings(stage_b_settings: dict) -> tuple[dict, dict]:
    """Separate PMONM schema-owned settings from Marshfield Stage B metadata."""

    stage_b_payload = stage_b_settings.get("settings", {}) or {}
    pmonm_settings = {}
    for section in (
        "settings",
        "dss",
        "bus",
        "load",
        "switch",
        "line",
        "transformer",
        "generator",
        "storage",
        "solar",
        "voltage_source",
        "options",
        "solvers",
    ):
        if section in stage_b_payload:
            pmonm_settings[section] = stage_b_payload[section]
    metadata = dict(stage_b_settings)
    return pmonm_settings, metadata


def _filter_stage_b_settings(stage_b_settings: dict, *, feeder_ids: set[str] | None) -> dict:
    """Keep only settings that refer to selected feeders in pilot exports."""

    if not feeder_ids:
        return stage_b_settings
    filtered = json.loads(json.dumps(stage_b_settings))
    settings = filtered.get("settings", {}) or {}
    switch_section = settings.get("switch")
    if isinstance(switch_section, dict):
        settings["switch"] = {
            name: value
            for name, value in switch_section.items()
            if any(str(name).startswith(f"{feeder_id}__") for feeder_id in feeder_ids)
            or any(str(value.get("switch_id", "")).find(feeder_id) >= 0 for feeder_id in feeder_ids)
        }
    microgrid_section = settings.get("microgrid")
    if isinstance(microgrid_section, dict):
        settings["microgrid"] = {
            name: value
            for name, value in microgrid_section.items()
            if any(feeder_id in str(name) for feeder_id in feeder_ids)
        }
    filtered["settings"] = settings
    return filtered


def build_powermodels_onm_export(
    *,
    feeder_opendss_dir: Path,
    smart_ds_compat_dir: Path,
    output_dir: Path,
    asset_registry_dir: Path | None = None,
    feeder_ids: Sequence[str] | None = None,
) -> PowerModelsOnmExport:
    """Build a single OpenDSS entrypoint and companions for PowerModelsONM.

    The adapter operates from canonical artifacts instead of the notebook-only
    in-memory GDM objects. It prefixes per-feeder bus names so cross-feeder ties
    and sectionalizers attach to the same namespace used by Stage B artifacts.
    """

    output_dir.mkdir(parents=True, exist_ok=True)

    asset_registry_dir = (
        asset_registry_dir
        if asset_registry_dir is not None
        else feeder_opendss_dir.parent.parent / "asset_registry"
    )
    selected_feeder_ids = {str(feeder_id) for feeder_id in feeder_ids or []}
    sources = pd.read_csv(asset_registry_dir / "sources.csv")
    if selected_feeder_ids and "feeder_id" in sources.columns:
        sources = sources[sources["feeder_id"].astype(str).isin(selected_feeder_ids)].copy()
    feeder_dirs = sorted(path for path in feeder_opendss_dir.iterdir() if path.is_dir())
    if selected_feeder_ids:
        feeder_dirs = [path for path in feeder_dirs if path.name in selected_feeder_ids]
    if not feeder_dirs:
        raise FileNotFoundError(f"no feeder OpenDSS directories under {feeder_opendss_dir}")
    if sources.empty:
        raise ValueError("no voltage sources remain after applying selected feeder_ids")

    linecodes_path = output_dir / "LineCodes.dss"
    transformers_path = output_dir / "Transformers.dss"
    lines_path = output_dir / "Lines.dss"
    loads_path = output_dir / "Loads.dss"
    loadshapes_path = output_dir / "LoadShapes.dss"
    ders_path = output_dir / "DERs.dss"
    switches_path = output_dir / "Switches.dss"
    buscoords_path = output_dir / "BusCoords.dss"
    settings_path = output_dir / "settings.json"
    stage_b_metadata_path = output_dir / "stage_b_onm_metadata.json"
    network_dss_path = output_dir / "network.dss"
    manifest_path = output_dir / "manifest.json"

    switches = pd.read_parquet(smart_ds_compat_dir / "controllable_switches.parquet")
    if selected_feeder_ids and "feeder_id" in switches.columns:
        switches = switches[switches["feeder_id"].astype(str).isin(selected_feeder_ids)].copy()
    replaced_line_names = set(
        switches.loc[
            switches["opens_existing_line"].fillna(False),
            "associated_line_name",
        ].dropna().astype(str)
    )
    profiles_dir = output_dir / "profiles"
    loadshape_by_load_name, loadshapes_text = _loadshape_assignments(
        smart_ds_compat_dir=smart_ds_compat_dir,
        asset_registry_dir=asset_registry_dir,
        profiles_dir=profiles_dir,
    )
    ders_text, der_export_counts, der_dss_settings = _der_generators_text(
        smart_ds_compat_dir=smart_ds_compat_dir,
        feeder_ids=selected_feeder_ids or None,
    )

    for filename, destination in [
        ("LineCodes.dss", linecodes_path),
        ("Transformers.dss", transformers_path),
        ("Lines.dss", lines_path),
    ]:
        chunks = [
            _prefixed_component_text(feeder_dir, filename, feeder_dir.name)
            for feeder_dir in feeder_dirs
        ]
        if filename == "LineCodes.dss":
            chunks = [_normalize_linecode_impedance_text(chunk) for chunk in chunks]
        if filename == "Lines.dss":
            chunks = [_drop_named_lines(chunk, replaced_line_names) for chunk in chunks]
        destination.write_text("\n".join(chunk for chunk in chunks if chunk) + "\n", encoding="utf-8")

    load_chunks = []
    for feeder_dir in feeder_dirs:
        load_text = _prefixed_component_text(feeder_dir, "Loads.dss", feeder_dir.name)
        load_chunks.append(
            "\n".join(
                _append_yearly_loadshape(line, loadshape_by_load_name)
                for line in load_text.splitlines()
            )
        )
    loads_path.write_text("\n".join(chunk for chunk in load_chunks if chunk) + "\n", encoding="utf-8")

    buscoords_path.write_text(
        "\n".join(
            chunk
            for chunk in (
                _prefixed_buscoords_text(feeder_dir, feeder_dir.name)
                for feeder_dir in feeder_dirs
            )
            if chunk
        )
        + "\n",
        encoding="utf-8",
    )
    loadshapes_path.write_text(
        loadshapes_text or "! No critical-load LoadShape assignments materialized.\n",
        encoding="utf-8",
    )
    ders_path.write_text(
        ders_text or "! No assigned grid-forming DER rows available for export.\n",
        encoding="utf-8",
    )
    stage_b_settings = json.loads((smart_ds_compat_dir / "onm_settings.json").read_text(encoding="utf-8"))
    stage_b_settings = _filter_stage_b_settings(
        stage_b_settings,
        feeder_ids=selected_feeder_ids or None,
    )
    pmonm_settings, stage_b_metadata = _split_pmonm_settings(stage_b_settings)
    if der_dss_settings:
        pmonm_settings.setdefault("dss", {}).update(der_dss_settings)
    settings_path.write_text(json.dumps(pmonm_settings, indent=2, sort_keys=True), encoding="utf-8")
    stage_b_metadata_path.write_text(json.dumps(stage_b_metadata, indent=2, sort_keys=True), encoding="utf-8")
    switches_path.write_text(
        _switches_text_without_disable_commands_from_text(render_switches_dss(switches)),
        encoding="utf-8",
    )

    first_source = sources.iloc[0]
    network_lines = [
        "Clear",
        (
            "New Circuit.marshfield_onm "
            f"Bus1={first_source['bus']} BasekV={float(first_source['basekv'])} "
            f"pu={float(first_source['pu'])} Angle={float(first_source['angle'])} "
            f"Phases={int(first_source['phases'])} {_fault_study_source_impedance}"
        ),
    ]
    for row in sources.iloc[1:].itertuples(index=False):
        network_lines.append(
            f"New Vsource.{row.source_name} Bus1={row.bus} BasekV={float(row.basekv)} "
            f"pu={float(row.pu)} Angle={float(row.angle)} Phases={int(row.phases)} "
            f"{_fault_study_source_impedance}"
        )
    network_lines.extend(
        [
            "redirect LineCodes.dss",
            "redirect Transformers.dss",
            "redirect Lines.dss",
            "redirect LoadShapes.dss",
            "redirect Loads.dss",
            "redirect DERs.dss",
            "redirect Switches.dss",
            "Set Voltagebases=[0.20784, 12.4704]",
            "calcv",
            "Solve",
            "redirect BusCoords.dss",
        ]
    )
    network_dss_path.write_text("\n".join(network_lines) + "\n", encoding="utf-8")

    manifest = {
        "schema_version": "marshfield_powermodels_onm_export.v0.1",
        "network_dss": str(network_dss_path),
        "settings": str(settings_path),
        "stage_b_onm_metadata": str(stage_b_metadata_path),
        "feeder_count": len(feeder_dirs),
        "source_count": len(sources),
        "export_scope": "pilot" if selected_feeder_ids else "full",
        "selected_feeder_ids": sorted(selected_feeder_ids),
        "gdm_bridge": {
            "package": "gdm",
            "available": True,
            "role": "baseline construction context; export rebuilt from canonical OpenDSS/Parquet artifacts",
        },
        "der_export": {
            "reopt_sized_rows": der_export_counts["reopt_sized"],
            "not_reopt_sized_provisional_rows": der_export_counts["provisional"],
            "provisional_capacity_policy": "critical_load_fraction_times_profile_peak",
        },
    }
    manifest_path.write_text(json.dumps(manifest, indent=2, sort_keys=True), encoding="utf-8")

    return PowerModelsOnmExport(
        output_dir=output_dir,
        network_dss_path=network_dss_path,
        settings_path=settings_path,
        linecodes_path=linecodes_path,
        transformers_path=transformers_path,
        lines_path=lines_path,
        loads_path=loads_path,
        loadshapes_path=loadshapes_path,
        ders_path=ders_path,
        switches_path=switches_path,
        buscoords_path=buscoords_path,
        stage_b_metadata_path=stage_b_metadata_path,
        manifest_path=manifest_path,
    )


def export_powermodels_onm(
    *,
    opendss_root: Path,
    asset_registry_dir: Path,
    blocks: pd.DataFrame,
    switches: pd.DataFrame,
    der_inventory: pd.DataFrame,
    load_profiles: pd.DataFrame,
    output_dir: Path,
) -> dict:
    """Notebook-facing PowerModelsONM export from in-memory artifact frames."""

    smart_ds_compat_dir = output_dir.parent / "augmented"
    smart_ds_compat_dir.mkdir(parents=True, exist_ok=True)

    blocks.to_parquet(smart_ds_compat_dir / "switch_bounded_load_blocks.parquet", index=False)
    switches.to_parquet(smart_ds_compat_dir / "controllable_switches.parquet", index=False)
    der_inventory.to_parquet(smart_ds_compat_dir / "der_inventory.parquet", index=False)
    load_profiles.to_parquet(smart_ds_compat_dir / "load_profile_assignments.parquet", index=False)

    (smart_ds_compat_dir / "switches.dss").write_text(
        render_switches_dss(switches),
        encoding="utf-8",
    )
    onm_settings = render_onm_settings(switches)
    onm_settings.setdefault("settings", {})["microgrid"] = _microgrid_settings_from_blocks(blocks)
    (smart_ds_compat_dir / "onm_settings.json").write_text(
        json.dumps(onm_settings, indent=2, sort_keys=True),
        encoding="utf-8",
    )

    export = build_powermodels_onm_export(
        feeder_opendss_dir=opendss_root,
        smart_ds_compat_dir=smart_ds_compat_dir,
        output_dir=output_dir,
        asset_registry_dir=asset_registry_dir,
    )
    return json.loads(export.manifest_path.read_text(encoding="utf-8"))


def _microgrid_settings_from_blocks(blocks: pd.DataFrame) -> dict[str, dict]:
    microgrids: dict[str, dict] = {}
    for row in blocks.itertuples(index=False):
        block_id = str(row.block_id)
        buses_json = getattr(row, "buses_json", "[]")
        try:
            buses = json.loads(buses_json)
        except TypeError:
            buses = []
        microgrids[block_id] = {
            "buses": buses,
            "load_kw": float(getattr(row, "load_kw", 0.0) or 0.0),
            "voltage_source_reachability": str(
                getattr(row, "voltage_source_reachability", "unknown")
            ),
        }
    return microgrids


# ONM contingency events

"""PowerModelsONM events.json serializer.

Converts the per-asset survival trajectory in ``asset_states.parquet`` into
the input PMONM uses to schedule restoration actions over the optimization
horizon. PMONM ingests a list of timestamped contingency events
(``events.json``); each event tells the optimizer when a network element
changes status. This serializer emits one ``switch`` event per
``available -> failed`` transition, indexed by PMONM's 1-indexed
``timestep`` field.

Schema (PowerModelsONM input-events schema, R31 in
``simulated_data_protocol.md``):

    [
      {
        "timestep": <int, 1-indexed>,
        "event_type": "switch",
        "affected_asset": "<element_type>.<dss_name>",
        "event_data": {"dispatchable": "NO", "state": "OPEN", "status": "ENABLED"}
      }
    ]

Inputs:

* ``asset_states``: per-asset survival rows, as produced by
  ``power.exports.export_stage_a2`` for a fixed
  ``(event_id, mc_draw)``. The serializer filters to the requested
  ``(event_id, mc_draw)`` slice and ignores other rows.
* ``asset_to_dss_element``: mapping from Stage A1 ``asset_id`` to the
  OpenDSS element name PMONM will see. Assets without a mapping are
  recorded in ``skipped_asset_ids`` rather than silently dropped, because
  PMONM cannot operate an element it never parsed.

Timestep indexing: PMONM uses 1-indexed timesteps. We compute the PMONM
timestep from the ceiling of ``(timestamp - event_start_utc)`` in hours plus 1,
so an asset that is failed at the first sample emits a ``timestep = 1`` event.
"""


from collections.abc import Iterable, Mapping
from dataclasses import dataclass, field
from datetime import datetime, timezone
from typing import Any


onm_events_schema_version = "marshfield_onm_events.v0.1"


@dataclass(frozen=True)
class AssetStateRow:
    """One row of the Stage A2 asset-state trajectory.

    Constructed by the caller from ``asset_states.parquet`` rows; using a
    dataclass keeps the public interface explicit and the tracer test small.
    """

    event_id: str
    mc_draw: int
    timestamp: datetime
    asset_id: str
    state: str


@dataclass(frozen=True)
class OnmEventsResult:
    """Serializer output: events plus diagnostics."""

    events: list[dict[str, Any]]
    event_id: str
    mc_draw: int
    event_start_utc: datetime
    schema_version: str = onm_events_schema_version
    skipped_asset_ids: list[str] = field(default_factory=list)


def build_onm_events(
    asset_states: Iterable[AssetStateRow],
    *,
    event_id: str,
    mc_draw: int,
    asset_to_dss_element: Mapping[str, str],
    event_start_utc: datetime,
) -> OnmEventsResult:
    """Build the PMONM events.json payload for one (event_id, mc_draw) slice."""

    if event_start_utc.tzinfo is None:
        raise ValueError("event_start_utc must be timezone-aware (UTC)")
    event_start_utc = event_start_utc.astimezone(timezone.utc)

    relevant = [
        row
        for row in asset_states
        if row.event_id == event_id and row.mc_draw == mc_draw
    ]

    by_asset: dict[str, list[AssetStateRow]] = {}
    for row in relevant:
        by_asset.setdefault(row.asset_id, []).append(row)

    events: list[dict[str, Any]] = []
    skipped: list[str] = []

    for asset_id, rows in by_asset.items():
        rows_sorted = sorted(rows, key=lambda item: item.timestamp)
        transition_row = _first_failure_transition(rows_sorted)
        if transition_row is None:
            continue
        dss_element = asset_to_dss_element.get(asset_id)
        if dss_element is None:
            skipped.append(f"missing_dss_mapping_for_{asset_id}")
            continue
        timestep = _pmonm_timestep(transition_row.timestamp, event_start_utc)
        events.append(
            {
                "timestep": timestep,
                "event_type": "switch",
                "affected_asset": dss_element,
                "event_data": {
                    "dispatchable": "NO",
                    "state": "OPEN",
                    "status": "ENABLED",
                },
            }
        )

    events.sort(key=lambda item: (item["timestep"], item["affected_asset"]))

    return OnmEventsResult(
        events=events,
        event_id=event_id,
        mc_draw=mc_draw,
        event_start_utc=event_start_utc,
        skipped_asset_ids=skipped,
    )


def _first_failure_transition(rows: list[AssetStateRow]) -> AssetStateRow | None:
    previous_state: str | None = None
    for row in rows:
        if row.state == "failed" and previous_state != "failed":
            return row
        previous_state = row.state
    return None


def _pmonm_timestep(transition_time: datetime, event_start: datetime) -> int:
    transition_utc = transition_time.astimezone(timezone.utc)
    delta_hours = (transition_utc - event_start).total_seconds() / 3600.0
    return max(1, int(delta_hours) + 1)


def build_asset_to_dss_element_map(
    *,
    assets: pd.DataFrame,
    controllable_switches: pd.DataFrame | None = None,
) -> dict[str, str]:
    """Map Marshfield asset ids to DSS element names visible to PowerModelsONM."""

    class_by_table = {
        "lines": "line",
        "line": "line",
        "switches": "line",
        "transformers": "transformer",
        "loads": "load",
        "load_buses": "load",
        "generators": "generator",
        "storage": "storage",
        "solar": "pvsystem",
    }
    mapping: dict[str, str] = {}
    if not assets.empty:
        for row in assets.itertuples(index=False):
            source_table = str(getattr(row, "source_asset_table", "") or "")
            source_name = str(getattr(row, "source_asset_name", "") or "")
            asset_id = str(getattr(row, "asset_id", "") or "")
            dss_class = class_by_table.get(source_table)
            if asset_id and dss_class and source_name and source_name != "nan":
                mapping[asset_id] = f"{dss_class}.{source_name}"

    if controllable_switches is not None and not controllable_switches.empty:
        for row in controllable_switches.itertuples(index=False):
            switch_id = str(getattr(row, "switch_id", "") or "")
            opendss_element = str(getattr(row, "opendss_element", "") or "")
            if switch_id and "." in opendss_element:
                dss_class, name = opendss_element.split(".", 1)
                mapping[switch_id] = f"{dss_class.lower()}.{name}"
    return mapping


def _asset_state_rows_from_frame(asset_states: pd.DataFrame) -> list[AssetStateRow]:
    rows: list[AssetStateRow] = []
    for row in asset_states.itertuples(index=False):
        timestamp = getattr(row, "timestamp")
        if not isinstance(timestamp, datetime):
            timestamp = pd.Timestamp(timestamp).to_pydatetime()
        rows.append(
            AssetStateRow(
                event_id=str(getattr(row, "event_id")),
                mc_draw=int(getattr(row, "mc_draw")),
                timestamp=_coerce_utc(timestamp),
                asset_id=str(getattr(row, "asset_id")),
                state=str(getattr(row, "state")),
            )
        )
    return rows


def materialize_onm_run_bundle(
    *,
    export_dir: Path,
    smart_ds_compat_dir: Path,
    event_id: str,
    mc_draw: int,
    event_start: datetime,
    horizon_hours: int = default_fema_lifelines_horizon_hours,
    asset_states: pd.DataFrame | Iterable[AssetStateRow] | None = None,
    asset_to_dss_element: Mapping[str, str] | None = None,
    uncertainty_band: float = default_load_uncertainty_band_fraction,
) -> OnmRunBundle:
    """Write the event-window sidecar files consumed by PMONM/DynaGrid runs."""

    export_dir = Path(export_dir)
    smart_ds_compat_dir = Path(smart_ds_compat_dir)
    bundle_dir = export_dir / "events" / event_id / f"draw_{int(mc_draw)}"
    bundle_dir.mkdir(parents=True, exist_ok=True)

    load_profiles = pd.read_parquet(smart_ds_compat_dir / "load_profile_assignments.parquet")
    blocks = pd.read_parquet(smart_ds_compat_dir / "switch_bounded_load_blocks.parquet")
    bundle = build_event_window_bundle(
        event_start=event_start,
        horizon_hours=horizon_hours,
        load_profiles=load_profiles,
        blocks=blocks,
        sandbox_id="marshfield",
        uncertainty_band=uncertainty_band,
        event_id=event_id,
        mc_draw=mc_draw,
    )

    if asset_states is None:
        event_rows: list[AssetStateRow] = []
    elif isinstance(asset_states, pd.DataFrame):
        event_rows = _asset_state_rows_from_frame(asset_states)
    else:
        event_rows = list(asset_states)

    if asset_to_dss_element is None:
        assets_path = smart_ds_compat_dir / "assets.parquet"
        switches_path = smart_ds_compat_dir / "controllable_switches.parquet"
        asset_to_dss_element = build_asset_to_dss_element_map(
            assets=pd.read_parquet(assets_path) if assets_path.exists() else pd.DataFrame(),
            controllable_switches=pd.read_parquet(switches_path) if switches_path.exists() else None,
        )

    events_result = build_onm_events(
        event_rows,
        event_id=event_id,
        mc_draw=mc_draw,
        asset_to_dss_element=asset_to_dss_element,
        event_start_utc=_coerce_utc(event_start),
    )

    events_path = bundle_dir / "events.json"
    runtime_args_path = bundle_dir / "runtime_args.json"
    nominal_load_window_path = bundle_dir / "nominal_load_window.json"
    load_uncertainty_path = bundle_dir / "load_uncertainty.json"
    block_demand_summary_path = bundle_dir / "block_demand_summary.json"
    run_manifest_path = bundle_dir / "run_manifest.json"

    events_path.write_text(json.dumps(events_result.events, indent=2, sort_keys=True), encoding="utf-8")
    runtime_args = {
        "network": str(export_dir / "network.dss"),
        "settings": str(export_dir / "settings.json"),
        "events": str(events_path),
        "output": str(bundle_dir / "powermodels_onm_output.json"),
        "nprocs": 1,
        "skip": ["faults", "stability"],
    }
    runtime_args_path.write_text(json.dumps(runtime_args, indent=2, sort_keys=True), encoding="utf-8")
    nominal_load_window_path.write_text(
        json.dumps(
            {
                "event_id": event_id,
                "mc_draw": int(mc_draw),
                "event_start": bundle["event_start"],
                "event_end": bundle["event_end"],
                "horizon_hours": bundle["horizon_hours"],
                "timestep_count": bundle["timestep_count"],
                "units": "kW",
                "loads": bundle["nodal_demand"],
            },
            indent=2,
            sort_keys=True,
        ),
        encoding="utf-8",
    )
    load_uncertainty_path.write_text(
        json.dumps(
            {
                "event_id": event_id,
                "mc_draw": int(mc_draw),
                "units": "kW",
                "bounds": bundle["uncertainty_bands"],
            },
            indent=2,
            sort_keys=True,
        ),
        encoding="utf-8",
    )
    block_demand_summary_path.write_text(
        json.dumps(bundle["block_demand_summary"], indent=2, sort_keys=True),
        encoding="utf-8",
    )
    run_manifest = {
        "schema_version": "marshfield_onm_run_bundle.v0.1",
        "event_id": event_id,
        "mc_draw": int(mc_draw),
        "event_start": bundle["event_start"],
        "event_end": bundle["event_end"],
        "horizon_hours": bundle["horizon_hours"],
        "timestep_count": bundle["timestep_count"],
        "network": str(export_dir / "network.dss"),
        "settings": str(export_dir / "settings.json"),
        "events": str(events_path),
        "runtime_args": str(runtime_args_path),
        "nominal_load_window": str(nominal_load_window_path),
        "load_uncertainty": str(load_uncertainty_path),
        "block_demand_summary": str(block_demand_summary_path),
        "event_count": len(events_result.events),
        "skipped_asset_ids": events_result.skipped_asset_ids,
        "uncertainty_band": uncertainty_band,
        "load_profile_count": bundle["load_profile_count"],
        "block_count": bundle["block_count"],
        "weather_years": bundle["weather_years"],
    }
    run_manifest_path.write_text(json.dumps(run_manifest, indent=2, sort_keys=True), encoding="utf-8")

    return OnmRunBundle(
        bundle_dir=bundle_dir,
        events_path=events_path,
        runtime_args_path=runtime_args_path,
        nominal_load_window_path=nominal_load_window_path,
        load_uncertainty_path=load_uncertainty_path,
        block_demand_summary_path=block_demand_summary_path,
        run_manifest_path=run_manifest_path,
    )


# Julia/PowerModelsONM smoke runner

"""Artifact-first Python adapters for repo-local Julia toolchains."""


import json
import os
import subprocess
from dataclasses import dataclass
from pathlib import Path
from os import PathLike


@dataclass(frozen=True)
class JuliaToolchainResult:
    """Result emitted by a Julia toolchain adapter."""

    output_json: Path
    command: list[str]
    stdout: str
    stderr: str
    summary: dict


def _repo_root() -> Path:
    return Path(__file__).resolve().parents[3]


def run_powermodels_onm_smoke(
    *,
    network_dss: Path | str,
    settings_json: Path | str,
    output_json: Path | str,
    events_json: Path | str | None = None,
    solve_mld: bool = False,
    julia_executable: PathLike[str] | str = "julia",
    julia_channel: str = "1.10",
    repo_root: Path | str | None = None,
    project_dir: Path | str = "julia/onm",
    script_path: Path | str = "scripts/julia/powermodels_onm_smoke.jl",
) -> JuliaToolchainResult:
    """Run the PowerModelsONM parser smoke gate through the Julia project."""

    root = Path(repo_root) if repo_root is not None else _repo_root()
    output_path = Path(output_json)
    command = [
        str(julia_executable),
        f"+{julia_channel}",
        f"--project={project_dir}",
        str(script_path),
        str(network_dss),
        str(settings_json),
        str(output_path),
    ]
    if events_json is not None:
        command.extend(["--events", str(events_json)])
    if solve_mld:
        command.append("--mld")
    completed = subprocess.run(
        command,
        cwd=root,
        check=True,
        capture_output=True,
        text=True,
    )
    summary = json.loads(output_path.read_text(encoding="utf-8"))
    return JuliaToolchainResult(
        output_json=output_path,
        command=command,
        stdout=completed.stdout,
        stderr=completed.stderr,
        summary=summary,
    )


def run_dynagrid_smoke(
    *,
    network_dss: Path | str,
    settings_json: Path | str,
    output_json: Path | str,
    events_json: Path | str | None = None,
    nrel_dynagrid_path: Path | str | None = None,
    julia_executable: PathLike[str] | str = "julia",
    julia_channel: str = "1.10",
    repo_root: Path | str | None = None,
    project_dir: Path | str = "julia/onm",
    script_path: Path | str = "scripts/julia/dynagrid_smoke.jl",
) -> JuliaToolchainResult:
    """Run the NRELDynaGrid online-control smoke gate through Julia."""

    root = Path(repo_root) if repo_root is not None else _repo_root()
    output_path = Path(output_json)
    command = [
        str(julia_executable),
        f"+{julia_channel}",
        f"--project={project_dir}",
        str(script_path),
        str(network_dss),
        str(settings_json),
        str(output_path),
    ]
    if events_json is not None:
        command.extend(["--events", str(events_json)])
    env = None
    if nrel_dynagrid_path is not None:
        env = dict(os.environ)
        env["NRELDYNAGRID_PATH"] = str(nrel_dynagrid_path)
    completed = subprocess.run(
        command,
        cwd=root,
        env=env,
        check=True,
        capture_output=True,
        text=True,
    )
    summary = json.loads(output_path.read_text(encoding="utf-8"))
    return JuliaToolchainResult(
        output_json=output_path,
        command=command,
        stdout=completed.stdout,
        stderr=completed.stderr,
        summary=summary,
    )
