project:
  name: austin
  place_name: Austin, TX, USA
  country: US
  model_crs: EPSG:32614
  reference_crs: EPSG:4326

# User-facing location mode and driver selection.
flood_setting: inland

event_drivers:
- rainfall
- streamflow
- soil_moisture

coastal_waves: false

includes:
  smartds: smartds.yaml
  sfincs: sfincs.yaml
  wflow: wflow.yaml
