"""Power-system substrates, catalogs, assets, and telemetry adapters."""

from power.blocks import (
    Block,
    BlockInvariantViolation,
    SWITCH_BOUNDED_LOAD_BLOCKS_SCHEMA_VERSION,
    build_block_artifact_rows,
    derive_validated_blocks,
    inject_block_ids_into_onm_settings,
    label_bus_voltage_classes,
)
from power.critical_loads import (
    CRITICAL_LOAD_ASSIGNMENTS_SCHEMA_VERSION,
    CriticalLoadAssignmentViolation,
    build_critical_load_assignments,
    critical_load_assignments_pyarrow_schema,
    validate_critical_load_assignments,
)
from power.der_inventory import (
    DEFAULT_ELECTRIC_TARIFF,
    DEFAULT_REOPT_LOAD_YEAR,
    DEFAULT_TIER_CLF_MAP,
    DERAssignmentViolation,
    FEMA_COMMUNITY_LIFELINES_OUTAGE_HOURS,
    HOURS_PER_YEAR,
    MHMP_BACKED_STATUSES,
    PLACEMENT_RULE_LAYER_1,
    PLACEMENT_RULE_LAYER_2,
    ReoptSizingInputViolation,
    SCHEMA_VERSION as DER_INVENTORY_SCHEMA_VERSION,
    apply_layer_2_reopt_sizing,
    build_layer_1_der_inventory,
    build_reopt_request_payload,
    build_synthetic_commercial_load_profile,
    der_inventory_pyarrow_schema,
    parse_reopt_results,
    validate_der_assignment_completeness,
    validate_reopt_sizing_inputs,
)
from power.load_profiles import (
    DEFAULT_ASHRAE_CLIMATE_ZONE,
    LOAD_PROFILE_ASSIGNMENTS_SCHEMA_VERSION,
    SYNTHETIC_PEAK_KW_BY_CLASS,
    TIER_INT_TO_STRING,
    LocationLoadProfileInputs,
    assign_archetype,
    build_archetype_load_profile,
    build_location_load_profile_inputs,
    build_load_profile_assignment_row,
    load_profile_assignments_pyarrow_schema,
)
from power.critical_facilities import (
    CRITICAL_FACILITY_COLUMNS,
    CRITICAL_FACILITY_SCHEMA_VERSION,
    empty_critical_facilities_gdf,
    load_critical_facilities,
    load_bus_electrical_metadata,
    write_critical_facilities_artifact,
)
from power.reopt_sizing import (
    CachedReoptResultsClient,
    ReoptSizingResult,
    run_layer_2_reopt_sizing,
)
from power.onm_export import (
    ONM_SETTINGS_SCHEMA_VERSION,
    connected_component_count,
    derive_switch_bounded_load_block_summary,
    render_onm_settings,
    render_switches_dss,
)
from power.powermodels_onm_export import (
    PowerModelsOnmExport,
    build_powermodels_onm_export,
)
from power.onm_readiness import (
    build_onm_readiness_report,
    summarize_der_export_readiness,
    summarize_opendss_solve_readiness,
    summarize_powermodels_onm_smoke_readiness,
)
from power.onm_run import (
    ONM_RUN_SCHEMA_VERSION,
    NodalAnnualProfile,
    OnmEventArtifacts,
    build_onm_event_window_artifacts,
)
from power.julia_toolchain import (
    JuliaToolchainResult,
    run_powermodels_onm_smoke,
)
from power.reopt_client import (
    REOPT_BASE_URL,
    ReoptClient,
    ReoptError,
    default_reopt_client,
    load_nlr_api_key,
)
from power.stock_profiles import (
    OediProfileSelection,
    load_oedi_8760_profile_kw,
    select_oedi_profile,
)
from power.tariffs import (
    UrdbTariffSelection,
    select_eversource_south_shore_tariff,
)
from power.ssap import (
    CONTROLLABLE_SWITCHES_SCHEMA_VERSION,
    PLACEMENT_RULE_SSAP,
    RESILIENCE_SWITCH_PLACEMENT_CITATIONS,
    SSAP_CITATIONS,
    SSAP_SUBRULE,
    RootedFeeder,
    SsapCandidatePolicy,
    SsapEdge,
    SsapFrontierPoint,
    SsapGlobalMarginalSelection,
    SsapSolution,
    SsapZone,
    TWO_TIER_SWITCH_CITATIONS,
    build_customer_weighted_loads,
    build_rooted_feeder_from_tables,
    classify_two_tier_switches,
    build_rooted_feeders_from_tables,
    derive_switch_bounded_blocks,
    emit_ssap_switch_rows,
    homogenize_feeder_exposure,
    select_global_marginal_benefit_budget,
    solve_rpop_ready_ssap_frontier,
    solve_rpop_ready_ssap,
    solve_ssap_per_feeder,
)
from power.smart_ds import SmartDsDownloadPlanItem
from power.smart_ds import SmartDsModelRef
from power.smart_ds import get_smart_ds_urls
from power.smart_ds import oedi_bucket
from power.smart_ds import oedi_s3_base_url
from power.smart_ds import smart_ds_download_plan
from power.smart_ds import smart_ds_model_dir
from power.smart_ds import smart_ds_models
from power.smart_ds import valid_years

__all__ = [
    "Block",
    "BlockInvariantViolation",
    "SWITCH_BOUNDED_LOAD_BLOCKS_SCHEMA_VERSION",
    "build_block_artifact_rows",
    "inject_block_ids_into_onm_settings",
    "CONTROLLABLE_SWITCHES_SCHEMA_VERSION",
    "CRITICAL_LOAD_ASSIGNMENTS_SCHEMA_VERSION",
    "CRITICAL_FACILITY_COLUMNS",
    "CRITICAL_FACILITY_SCHEMA_VERSION",
    "CachedReoptResultsClient",
    "CriticalLoadAssignmentViolation",
    "DEFAULT_ASHRAE_CLIMATE_ZONE",
    "DEFAULT_ELECTRIC_TARIFF",
    "DEFAULT_REOPT_LOAD_YEAR",
    "DEFAULT_TIER_CLF_MAP",
    "DERAssignmentViolation",
    "DER_INVENTORY_SCHEMA_VERSION",
    "FEMA_COMMUNITY_LIFELINES_OUTAGE_HOURS",
    "HOURS_PER_YEAR",
    "LOAD_PROFILE_ASSIGNMENTS_SCHEMA_VERSION",
    "SYNTHETIC_PEAK_KW_BY_CLASS",
    "MHMP_BACKED_STATUSES",
    "OediProfileSelection",
    "ONM_SETTINGS_SCHEMA_VERSION",
    "ONM_RUN_SCHEMA_VERSION",
    "PLACEMENT_RULE_LAYER_1",
    "PLACEMENT_RULE_LAYER_2",
    "PLACEMENT_RULE_SSAP",
    "REOPT_BASE_URL",
    "RESILIENCE_SWITCH_PLACEMENT_CITATIONS",
    "TWO_TIER_SWITCH_CITATIONS",
    "TIER_INT_TO_STRING",
    "LocationLoadProfileInputs",
    "ReoptSizingResult",
    "classify_two_tier_switches",
    "RootedFeeder",
    "SSAP_CITATIONS",
    "SSAP_SUBRULE",
    "SsapCandidatePolicy",
    "SsapEdge",
    "SsapFrontierPoint",
    "SsapGlobalMarginalSelection",
    "SsapSolution",
    "SsapZone",
    "UrdbTariffSelection",
    "ReoptClient",
    "ReoptError",
    "ReoptSizingInputViolation",
    "PowerModelsOnmExport",
    "NodalAnnualProfile",
    "OnmEventArtifacts",
    "JuliaToolchainResult",
    "SmartDsDownloadPlanItem",
    "SmartDsModelRef",
    "apply_layer_2_reopt_sizing",
    "assign_archetype",
    "build_archetype_load_profile",
    "build_critical_load_assignments",
    "build_layer_1_der_inventory",
    "build_load_profile_assignment_row",
    "build_location_load_profile_inputs",
    "build_powermodels_onm_export",
    "build_reopt_request_payload",
    "build_onm_readiness_report",
    "build_onm_event_window_artifacts",
    "build_customer_weighted_loads",
    "build_rooted_feeder_from_tables",
    "build_rooted_feeders_from_tables",
    "build_synthetic_commercial_load_profile",
    "critical_load_assignments_pyarrow_schema",
    "connected_component_count",
    "derive_switch_bounded_load_block_summary",
    "derive_switch_bounded_blocks",
    "derive_validated_blocks",
    "empty_critical_facilities_gdf",
    "label_bus_voltage_classes",
    "emit_ssap_switch_rows",
    "homogenize_feeder_exposure",
    "load_critical_facilities",
    "load_profile_assignments_pyarrow_schema",
    "load_bus_electrical_metadata",
    "load_oedi_8760_profile_kw",
    "select_global_marginal_benefit_budget",
    "select_eversource_south_shore_tariff",
    "select_oedi_profile",
    "summarize_der_export_readiness",
    "summarize_opendss_solve_readiness",
    "summarize_powermodels_onm_smoke_readiness",
    "solve_rpop_ready_ssap_frontier",
    "solve_rpop_ready_ssap",
    "solve_ssap_per_feeder",
    "default_reopt_client",
    "der_inventory_pyarrow_schema",
    "get_smart_ds_urls",
    "load_nlr_api_key",
    "oedi_bucket",
    "oedi_s3_base_url",
    "parse_reopt_results",
    "render_onm_settings",
    "render_switches_dss",
    "run_powermodels_onm_smoke",
    "run_layer_2_reopt_sizing",
    "smart_ds_download_plan",
    "smart_ds_model_dir",
    "smart_ds_models",
    "valid_years",
    "validate_critical_load_assignments",
    "validate_der_assignment_completeness",
    "validate_reopt_sizing_inputs",
    "write_critical_facilities_artifact",
]
