"""OpenDSS and PowerModelsONM export helpers for synthesized switches."""

from __future__ import annotations

import pandas as pd


ONM_SETTINGS_SCHEMA_VERSION = "stage_b_onm_settings.v0.1"


def render_switches_dss(controllable_switches: pd.DataFrame) -> str:
    """Render synthesized Controllable Switches as OpenDSS switch lines."""

    lines_out = [
        "! Marshfield Stage B synthesized Controllable Switches",
        "! Generated by add_infra.ipynb Infrastructure Step: controllable_switch_synthesis",
        "! Critical-load-boundary switches are deferred until critical-facility artifacts validate.",
    ]
    for row in controllable_switches.itertuples(index=False):
        element_name = row.opendss_element.split(".", 1)[1]
        action = "Open" if row.initial_state == "open" else "Close"
        normal = "Open" if row.normal_state == "open" else "Close"
        if row.switch_role == "sectionalizing" and bool(row.opens_existing_line):
            original_line = str(row.associated_line_name)
            linecode = str(row.associated_linecode) if pd.notna(row.associated_linecode) else ""
            units = str(row.associated_units) if pd.notna(row.associated_units) else "m"
            length_m = float(row.associated_length_m) if pd.notna(row.associated_length_m) else 2.0
            segment_length = max(length_m / 2.0, 0.001)
            linecode_clause = f" Linecode={linecode}" if linecode else ""
            switch_bus_a = f"{element_name}_a"
            switch_bus_b = f"{element_name}_b"
            lines_out.extend(
                [
                    f"Disable Line.{original_line}",
                    f"New Line.{element_name}_seg_a Bus1={row.from_bus} Bus2={switch_bus_a} Phases={row.phases}{linecode_clause} Length={segment_length:.6g} units={units}",
                    f"New Line.{element_name} Bus1={switch_bus_a} Bus2={switch_bus_b} Phases={row.phases} Switch=Yes",
                    "~ R1=0.001 X1=0 R0=0.001 X0=0 C1=0 C0=0 Length=0.001 units=km",
                    f"New SwtControl.{element_name} SwitchedObj=Line.{element_name} SwitchedTerm=1",
                    f"~ Action={action} Normal={normal} Lock=No",
                    f"New Line.{element_name}_seg_b Bus1={switch_bus_b} Bus2={row.to_bus} Phases={row.phases}{linecode_clause} Length={segment_length:.6g} units={units}",
                ]
            )
            continue
        lines_out.extend(
            [
                f"New Line.{element_name} Bus1={row.from_bus} Bus2={row.to_bus} Phases={row.phases} Switch=Yes",
                "~ R1=0.001 X1=0 R0=0.001 X0=0 C1=0 C0=0 Length=0.001 units=km",
                f"New SwtControl.{element_name} SwitchedObj=Line.{element_name} SwitchedTerm=1",
                f"~ Action={action} Normal={normal} Lock=No",
            ]
        )
    return "\n".join(lines_out) + "\n"


def render_onm_settings(controllable_switches: pd.DataFrame) -> dict:
    """Emit PowerModelsONM switch settings sidecar fields not expressible in DSS."""

    switch_section: dict[str, dict] = {}
    for row in controllable_switches.itertuples(index=False):
        switch_key = row.opendss_element.split(".", 1)[1]
        switch_section[switch_key] = {
            "dispatchable": "YES" if bool(row.dispatchable) else "NO",
            "status": "ENABLED" if str(row.status) == "enabled" else "DISABLED",
            "state": "OPEN" if str(row.normal_state) == "open" else "CLOSED",
            "switch_role": str(row.switch_role),
            "switch_id": str(row.switch_id),
        }
    return {
        "schema_version": ONM_SETTINGS_SCHEMA_VERSION,
        "infrastructure_step": "controllable_switch_synthesis",
        "settings": {
            "switch": switch_section,
        },
    }


def connected_component_count(
    edge_frame: pd.DataFrame,
    buses: pd.DataFrame,
    transformers: pd.DataFrame | None = None,
) -> tuple[int, pd.Series]:
    """Count connected bus components in an edge table."""

    parent = {bus: bus for bus in buses["bus"].dropna().unique()}

    def find(item):
        parent.setdefault(item, item)
        while parent[item] != item:
            parent[item] = parent[parent[item]]
            item = parent[item]
        return item

    def union(left, right):
        left_root = find(left)
        right_root = find(right)
        if left_root != right_root:
            parent[right_root] = left_root

    for edge in edge_frame.itertuples(index=False):
        union(edge.from_bus, edge.to_bus)

    if (
        transformers is not None
        and not transformers.empty
        and "winding_buses" in transformers.columns
    ):
        for row in transformers.itertuples(index=False):
            windings = [
                bus.strip()
                for bus in str(row.winding_buses).split(",")
                if bus.strip()
            ]
            unique: list[str] = []
            seen: set[str] = set()
            for bus in windings:
                if bus in seen:
                    continue
                seen.add(bus)
                unique.append(bus)
            if len(unique) < 2:
                continue
            hub = unique[0]
            for other in unique[1:]:
                union(hub, other)

    roots = pd.Series([find(bus) for bus in buses["bus"].dropna().unique()])
    sizes = roots.value_counts()
    return int(len(sizes)), sizes


def derive_switch_bounded_load_block_summary(
    lines: pd.DataFrame,
    buses: pd.DataFrame,
    controllable_switches: pd.DataFrame,
    transformers: pd.DataFrame | None = None,
) -> pd.Series:
    """Summarize static blocks after opening all synthesized sectionalizers.

    Transformer winding buses are non-switchable topology bridges per the
    Moring block abstraction, so they must connect components for this summary.
    """

    line_edges = lines[lines["line_class"].fillna("line").eq("line")].copy()
    baseline_components, _baseline_sizes = connected_component_count(
        line_edges, buses, transformers
    )
    opened_existing_lines = set(
        controllable_switches.loc[
            controllable_switches["opens_existing_line"].fillna(False),
            "associated_line_name",
        ].dropna()
    )
    block_edges = line_edges[~line_edges["line_name"].isin(opened_existing_lines)]
    block_count, block_sizes = connected_component_count(
        block_edges, buses, transformers
    )
    return pd.Series(
        {
            "baseline_components": baseline_components,
            "switch_bounded_blocks": block_count,
            "switch_bounded_nontrivial_blocks": int((block_sizes > 1).sum()),
            "switch_bounded_single_bus_blocks": int((block_sizes == 1).sum()),
            "median_block_bus_count": float(block_sizes.median()) if not block_sizes.empty else 0.0,
            "max_block_bus_count": int(block_sizes.max()) if not block_sizes.empty else 0,
            "opened_existing_lines_for_blocks": len(opened_existing_lines),
        }
    )
